config/routes.rb
MyVisualNovel::Application.routes.draw do


  resource :user_sessions
  match 'play/:id/null' => proc { [404, {}, ['']] }#for IE9 SoundManager
  match 'play/:id/:basename' => 'projects#play', :as=>:play
  resources :projects do
    resources :characters
    resources :scenes do
      member do
        post :update_event
        post :reorder
      end
      resources :events
    end
  end
  match 'projects/:project_id/toggle_character/:character_type' => 'characters#toggle', :as=>:toggle_character
  match 'events/:id/delete' => 'events#delete', :as => :delete_event
  match 'events/:id/moveup' => 'events#moveup', :as => :moveup_event
  match 'events/:id/movedown' => 'events#movedown', :as => :movedown_event
  match 'play/:id/:basename/scene/null' => proc { [404, {}, ['']] }#for IE9 SoundManager
  match 'play/:id/:basename/scene/:scene_id' => 'projects#play', :as=>:play_scene 

  resources :users do
    member do
      put :change_password
    end
  end

  match 'signup' => 'users#new', :as => :signup
  match 'logout' => 'user_sessions#destroy', :as => :logout
  match 'login' => 'user_sessions#new', :as => :login
  match 'main/terms' => 'main#terms_of_service', :as=>:terms_of_service
  match 'forum' => "main#forum", :as=>:forum
  match 'not_found' => 'main#not_found', :as => :not_found
  match 'main/cookie' => "main#cookie", :as=>:cookie
  match 'i' => "imager#get", :as=>:imager
  # match 'i/BackgroundImage/:folder/:filename.:format' => "imager#get", :as=>:imager
  root :to => 'main#index'


end

app/models/scene.rb
class Scene < ActiveRecord::Base
  belongs_to :project
  attr_accessor :initial_event_pack
  attr_accessible :custom_description, :initial_event_pack, :love_scene
  has_many :events, :dependent=>:delete_all
  validates_presence_of :project
  before_validation :set_order_index, :on=>:create
  after_destroy :reorder_indexes

  scope :ordered,  lambda { {:order=>"order_index ASC, id ASC"} }
  scope :for_project, lambda { |project| {:conditions => ["project_id=? ", project.id] } }


  scope :at, lambda { |order_index| {:conditions => ["order_index = ?", order_index], :limit=>1} }

  def reorder_indexes
    all = project.scenes.ordered.to_a
    all.each_index do |i|
      scene = all[i]
      scene.order_index = i+1
      scene.save if scene.changed?
    end
  end

  def move_to(order_index)
    scenes = project.scenes.to_a
    scenes.reject!{|scene|scene==self}
    scenes.insert(order_index, self)
    scenes.each_index do |i|
      scene = scenes[i]
      scene.order_index = i+1
      scene.save if scene.changed?
    end
  end

  def get_description
  	return custom_description if custom_description.present?
    out =  "#{image_at(middle_index).image_description}"
    out += " (love scene)" if love_scene?
    out
  end

  def load_initial_events
    if self.initial_event_pack.present?
      i = self.initial_event_pack.to_i
      scenes = EventPacks.locations(project)
      self.events = scenes[i].events
      self.custom_description = scenes[i].name
      
    end
  end

  def set_order_index
    self.order_index = Scene.maximum('order_index', :conditions => { :project_id => project_id }).to_i + 1
  end

  def middle_index
    (events.count.to_f/2).ceil
  end


   def image_at event_index
     if love_scene?
      Event.for_scene(self).at_or_before(event_index).love_poses.first || BackgroundImageEvent.default
     else
       Event.for_scene(self).at_or_before(event_index).background_images.first || BackgroundImageEvent.default
     end
   end

   def has_character? character, event_index
     if e = Event.for_scene(self).at(event_index).first
       return e.has_character? character
     end
     false
   end

   def get_ordered_events
    p = PreloadEvent.new.fill_data(self);
    [p,events.ordered.concat([SceneEndEvent.new])]
   end

end

app/controllers/scenes_controller.rb
class ScenesController < ApplicationController
  before_filter :get_scene, :only=>[:destroy, :edit, :update_event, :update, :reorder]
  # GET /scenes
  # GET /scenes.json
  def index
    @project = Project.find(params[:project_id])
    redirect_to project_path(@project) and return
    # @scenes = @project.scenes
    # @backlink = project_path(@project)

    # respond_to do |format|
    #   format.html # index.html.erb
    #   format.json { render json: @scenes }
    # end
  end

  def reorder

    @scene.move_to(params[:order_index].to_i)


     render json: @project 

  end

  # # GET /scenes/1
  # # GET /scenes/1.json
  # def show
  #   @scene = Scene.find(params[:id])
  #   @project = @scene.project
  #   @backlink = project_path(@project)

  #   respond_to do |format|
  #     format.html # show.html.erb
  #     format.json { render json: @scene }
  #   end
  # end

  # # GET /scenes/new
  # # GET /scenes/new.json
  # def new
  #   @scene = Scene.new

  #   respond_to do |format|
  #     format.html # new.html.erb
  #     format.json { render json: @scene }
  #   end
  # end

  # # GET /scenes/1/edit
  def edit
    @body_class = "scene-editor"
    @event_index =  params[:event_index] ? params[:event_index].to_i : @scene.events.count
    if params[:event_index].blank? && @scene.events.present?
      redirect_to :action=>:edit, :event_index=>@event_index #always scroll to current event
    end
    @event_count = @scene.events.count
    @event_index = [@event_index, @event_count].min
    @backlink = project_path(@project)
  end

  # # POST /scenes
  # # POST /scenes.json
  def create
    @project = Project.find(params[:project_id])
    if !@project.owner?(session_obj)
      not_authorized and return
    end
    @scene = @project.scenes.new(params[:scene])
    #load up initial background and music
    @scene.load_initial_events
    respond_to do |format|
      if @scene.save!
        format.html { redirect_to edit_project_scene_path(@project, @scene) }
        format.json { render json: @scene, status: :created, location: @scene }
      else
        flash[:notice] = @scene.errors.full_messages
        format.html { redirect_to :back }
        format.json { render json: @scene.errors, status: :unprocessable_entity }
      end
    end
  end

  def update_event
    @body_class = "scene-editor"

 #   @backlink = project_scenes_path(@project)
    @event = params[:event_id].present? ? Event.find(params[:event_id]) : @scene.events.new
    unless params[:event_id]
      flash[:notice] = "Good job! Add some more!"
    end
    respond_to do |format|
      if @event.update_attributes(params[:event])
        @event_index = @event.reload.order_index
        format.html { redirect_to action: "edit", event_index: @event_index, more_text: params[:more_text], more_text_type: params[:more_text_type]}
        format.json { head :no_content }
      else
        @event_index = @scene.events.count
        format.html { render action: "edit" }
        format.json { render json: @scene.errors, status: :unprocessable_entity }
      end
    end
  end

  # # PUT /scenes/1
  # # PUT /scenes/1.json
  def update

    respond_to do |format|
      if @scene.update_attributes(params[:scene])
        format.html { redirect_to edit_project_scene_path(@scene.project, @scene) }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @scene.errors, status: :unprocessable_entity }
      end
    end
  end

  # # DELETE /scenes/1
  # # DELETE /scenes/1.json
  def destroy

    @scene.destroy

    respond_to do |format|
      format.html { redirect_to action: "index" }
      format.json { head :no_content }
    end
  end

  def get_scene
    @scene = Scene.find_by_id(params[:id])
    if @scene.nil?
      not_found
      return false
    elsif !@scene.project.owner?(session_obj)
      not_authorized
      return false
    end
    @project = @scene.project
    true
  end
end

app/helpers/scenes_helper.rb
module ScenesHelper
    def to_sentence event
      if event.is_a?(NarrationEvent)
      	'<small class="detail muted">'.html_safe+event.detail+'</small>'.html_safe
      elsif event.glassbox?
      	event.to_sentence+'<br/><small class="detail">'.html_safe+event.detail+'</small>'.html_safe
      else
      	'<span class="muted">'.html_safe+event.to_sentence+'</span><br/><small class="detail muted">'.html_safe+event.detail+'</small>'.html_safe
      end
    	# <%unless event.is_a?(NarrationEvent)%>
	  		#   <span class='muted'><%=event.to_sentence%></span><br/>
	  		# <%end%>
	  		# <small class="detail"><%=event.detail%></small>
    end

	def event_to_js event
		if event.is_a?(CharacterPoseEvent) && @scene.love_scene?
		 "edit-pose"
		elsif event.is_a?(CharacterPoseEvent)
		 "edit-clothes"
		elsif event.is_a?(BackgroundImageEvent) ||  event.is_a?(LovePoseEvent)
		 "edit-bg-image"
		elsif event.is_a?(BackgroundMusicEvent)
		 "edit-music"
		else
		 "edit-speak"
	
		end
	end
	def event_to_command event
		if event.is_a?(CharacterPoseEvent) && @scene.love_scene?
		 " Change Pose"
		elsif event.is_a?(CharacterPoseEvent)
		 " Change Clothes"
		elsif event.is_a?(BackgroundImageEvent) || event.is_a?(LovePoseEvent)
		" Change Background"
		elsif event.is_a?(BackgroundMusicEvent)
		 " Change Music"
		else
		 " Edit Text"
		end
	end

	# def glass_box_class event
	# 	return "" if event && event.is_a?(CharacterSpeaksEvent) || event.is_a?(CharacterSpeaksEvent)
	# 	return "hide"
	# end
	# def narration_box_class event
	# 	return "" if event && event.is_a?(NarrationEvent) 
	# 	return "hide"
	# end
	def subcommand event
		return "" if @scene.love_scene?
		if event.is_a?(CharacterPoseEvent)
		  raw('<a data-character-id="'+event.character_id.to_s+'" href="#" class="btn btn-small edit-face"><i class="icon-pencil"></i> Change Face</a>')
		else
			""
		end
	end
end

app/views/scenes/_character_action_items.html.erb
				  	    <%present = @current_event.has_character?(character) %>
				  	    <div class="action-items-holder action-items-for-<%=character.id%> <%=present ? "char-present" : "char-missing"%>">
				  	      	<!-- This table is shown if they are present -->
				  	      <table class="action-items char-present">
					  	 	<tr>
					  	 	  <td rowspan=3 class="icon">
					  	 	  	<div class="btn tippable edit-speak" title="Click to make me talk!" data-character-id="<%=character.id%>" data-name="<%=character.name%>"><%=image_tag character.icon%></div>
					  	 	  </td>
					  	 	  <td class="btn btn-small">
					  	 	  	<a href="#" class="edit-speak" data-type="CharacterSpeaksEvent" data-character-id="<%=character.id%>" data-name="<%=character.name%>"><%=character.name%> speaks</a>
					  	 	  </td>
					  	 	</tr>
					  	 	<tr>
					  	 	  <td class="btn btn-small">
					  	 	  	<%if @scene.love_scene?%>
					  	 	  	  <a href="#" class="edit-pose" data-character-id="<%=character.id%>"><%=character.name%> changes pose</a>
					  	 	  	<%else%>
					  	 	  	  <a href="#" class="edit-face" data-character-id="<%=character.id%>"><%=character.name%> changes face</a>
					  	 	  	<%end%>
					  	 	  </td>
					  	 	</tr>
					  	 	<%if !@scene.love_scene?%>
					  	 	  <tr>
					  	 	  	<td class="btn btn-small">
					  	 		  <%=form_tag update_event_project_scene_path(@project, @scene)%>
						  	 		  <input type="hidden" name="event[type]" value="CharacterVanishEvent">
						  	 		  <input type="hidden" name="event[character_id]" value="<%=character.id%>">
						  	 		  <input type="hidden" name="event[order_index]" class="event_order" value="<%=@event_index%>">
						  	 		  <a href="#" class="submitable"><%=character.name%> vanishes</a>
					  	 	      </form>
					  	 	    </td>
					  	      </tr>
					  	 	<%end%>
				  	      </table>
				  	      <!-- This table is shown if they are missing! -->
				  	      <table class="action-items char-missing">
					  	 	<tr>
					  	 		<td class="btn btn-small">
					  	 			<a href="#" class="edit-<%=@scene.love_scene? ? "pose" : "clothes"%>" data-character-id="<%=character.id%>"><%=character.name%> appears</a>
					  	 		</td>
					  	 	</tr>
				  	      </table>
				  	    </div>

app/views/scenes/_form.html.erb
<%= form_for(@scene, :url => project_scene_path(@project.id, @scene.id)) do |f|%>
  <% if @scene.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@scene.errors.count, "error") %> prohibited this scene from being saved:</h2>

      <ul>
      <% @scene.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :project_id %><br />
    <%= f.number_field :project_id %>
  </div>
  <div class="field">
    <%= f.label :order_index %><br />
    <%= f.number_field :order_index %>
  </div>
  <div class="field">
    <%= f.label :custom_description %><br />
    <%= f.text_field :custom_description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/scenes/_thumbnail.html.erb
		
		<%play ||= false%>
		<%if scene%>
		  <%last_index = scene.events.count%>
	      <%event = Event.for_scene(scene).at(last_index).first%>
		<%elsif scene%>  
		  <%middle_index = scene.middle_index%>
	      <%event = Event.for_scene(scene).at(middle_index).first%>
	    <%end%>
	    <%if scene && event%>
	        <%=image_tag compiled_image(event, 260), :alt=>scene.get_description%>
		    <%if event.glassbox?%>
		      <%=image_tag "glassbox.png", :class=>"glass"%>
		      <div class="speaker"><%=event.character_name%></div>
			  <div class="textarea"><%=simple_format event.get_text%></div>
		    <%end%>

		  
		<%else%>
		  <%=image_tag BackgroundImageEvent.default.get_file%>
		<%end%>
		<%if play%>
		    <%=image_tag "play_cover.png", :class=>"glass"%>
		 <%end%>

app/views/scenes/edit.html.erb
<%content_for :javascript do%>
 <%=javascript_include_tag("soundmanager2/soundmanager2","inlineplayer")%>
<%end%>
<%
  current_event = Event.for_scene(@scene).at(@event_index).first || Event.new()
  bg_file =  current_event.try(:characters_present).try(:first).try(:second) || BackgroundImageEvent.default.get_file
%>
<table id="scene-editor">
	<tr>
		<td>
			
			  <p><b>Scene <%=@scene.order_index%>:</b> <%=@scene.get_description%></p>
			<table class="table table-condensed">
			  <tr><td>
			  	 <h2 class="no-monospace">Script</h2>
			  	 <div class="script-holder">
			  	 <table class="script table-bordered table-hover table-condensed">
			  	 	<tbody>
			  	 	<%if Event.for_scene(@scene).empty?%>
			  	 	  <tr><td>Nothing in the script yet.</td></tr>
			  	 	<%end%>
			  	 	<%Event.for_scene(@scene).ordered.each do |event|%>
			  	 	  <tr data-order-id="<%=event.order_index%>" data-id="<%=event.id%>" id="row<%=event.id%>">
			  	 	  	<td><%=event.order_index%></td>
			  	 	  	<td>
			  	 	  		<%if @event_index!=event.order_index%>
			  	 	  		  <div data-url="<%=edit_project_scene_url(@project, @scene, :event_index=>event.order_index)%>">
			  	 	  		<%end%>

			  	 	  		<%=to_sentence(event)%>
			  	 	  		<%#=event.characters_present%>
			  	 	  		

			  	 	  		<%if @event_index!=event.order_index%></div><%end%>
			  	 	  		
			  	 	  		<div class="more hide"><hr>
			  	 	  		<input type="hidden" class="event_text" value="<%=event.text%>">
			  	 	  		<a class="btn btn-small <%=event_to_js(event)%>" href="#" data-name="<%=event.get_character_name%>" data-type="<%=event.type%>" data-character-id="<%=event.character.try(:id)%>"><i class="icon-pencil"></i><%=event_to_command(event)%></a>
			  	 	  		  <%=subcommand(event)%>
			  	 	  		  <br/>
			  	 	  		  <%if event.order_index != 1%>
			  	 	  		    <a class="btn btn-small" href="<%=moveup_event_path(event)%>"><i class="icon-arrow-up"></i> Move Up</a>
			  	 	  		  <%end%><%if event.order_index != @event_count%>
			  	 	  		  <a class="btn btn-small" href="<%=movedown_event_path(event)%>"><i class="icon-arrow-down"></i> Move Down</a>
			  	 	  		  <%end%>
			  	 	  		  <a class="btn btn-small confirmable" href="<%=delete_event_path(event)%>"><i class="icon-remove"></i> Remove</a>
			  	 	  		</div>
			  	 	  	</td>
			  	 	  	<td width="28">
			  	 	  		<a class="btn btn-mini dropdown" href="#" title="Edit or Delete"><i class="icon-pencil"></i></a>
			  	 	  	</td>
			  	 	  </tr>
			  	 	<%end%>
			  	    </tbody>
			  	 </table></div> 
			  	 <h3>Add to the Script!</h3>
			  	<%character = @project.characters.where(:type=>"Narrator").first%>
	  	        <table class="action-items">
			  	 	<tr><td rowspan=3 class="icon"><span class="btn tippable edit-speak" title="Click to make me talk!" data-character-id="<%=character.id%>" data-name="<%=character.name%>"><%=image_tag character.icon%></span></td>
			  	 	<td class="btn btn-small"><a href="#" class="edit-speak" data-type="NarrationEvent" data-character-id="<%=character.id%>" data-name="">Narration</td></tr>
			  	 	<tr><td class="btn btn-small"><a href="#" class="edit-speak" data-type="CharacterThinksEvent" data-character-id="<%=character.id%>" data-name="<%=character.name%>"><%=character.name%> thinks</td></tr>
			  	 	<tr><td class="btn btn-small"><a href="#" class="edit-speak" data-type="CharacterSpeaksEvent" data-character-id="<%=character.id%>" data-name="<%=character.name%>"><%=character.name%> speaks</a></td></tr>
	  	        </table>
	  	        	   <%@current_event = current_event%>
		  	        	<%if num = current_event.characters_present.try(:second).try(:first)%>
		  	        	  <%=render :partial=>"character_action_items", :locals=>{:character=>Character.find(num)}%>
		  	        	<%end%>
		  	        	<%if num = current_event.characters_present.try(:third).try(:first)%>
		  	        	  <%=render :partial=>"character_action_items", :locals=>{:character=>Character.find(num)}%>
		  	        	<%end%>
		  	   
					  	<%@project.characters.without_narrator.each do |character|%>
					  	  <!-- show present characters first, then non-present characters -->
					  	  <%if !current_event.has_character?(character)%>
					  	    <%=render :partial=>"character_action_items", :locals=>{:character=>character}%>
					  	  <%end%>
						<%end%>
					

			  	 <table class="action-items">
			  	 	<tr>
			  	 	  <td rowspan=4 class="icon"><div class="btn"><%=image_tag bg_file%> </div></td>
			  	 	  <td class="btn btn-small"><a href="#" class="edit-bg-image">Background changes</a></td>
			  	 	</tr>
			  	 	<tr><td class="btn btn-small"><a href="#" class="edit-music">Music changes</a></td></tr>
			  	 	<tr><td class="btn btn-small"><%=link_to "Preview!", play_scene_path(@project, @project.basename, @scene)%></td></tr>
			  	 	
			  	 </table>
			  </td></tr>
			</table>
			<%=form_for [@project, @scene] do |f|%>
			  <%=f.hidden_field :custom_description, :value=>@scene.get_description, :class=>"nameable"%>
			  <a class="btn btn-small change-name">Change Scene Name</a>
		    <%end%>
		    <%= form_for([@project, @scene], :method => :delete) do |f|%>   
			  <a class="btn btn-small delete-scene">Delete Scene</a>
			<%end%>
		</td>
		<td>
		  <div class="mini-editor">

		  	<!-- Stage Viewer -->
		    <div class="mini-viewer">
		      
			  

			    <%=image_tag "#", :class=>"bg"%>

			  
			    <!-- edit text -->
			    <div class="glassbox" style="visibility:hidden">
			    	<%=image_tag "glassbox.png", :class=>"glass"%>
			    	<div class="speaker"></div>
			    	<div class="textarea"></div>

			    	  <%=form_tag update_event_project_scene_path(@project, @scene)%>
			    	  <textarea name="event[text]" value="" class="hide"></textarea>
			    	  <input type="hidden" name="event[order_index]" class="event_order" value="<%=@event_index%>">
			    	  <input type="hidden" name="event[type]" class="event_type" value="">
			    	  <input type="hidden" name="event_id" class="event_id" value="">
			    	  <input type="hidden" name="event[character_id]" class="character_id" value="">
			    	  <input type="hidden" name="more_text" class="more_text" value="">
			    	  <input type="hidden" name="more_text_type" class="more_text_type" value="">
			    	  <!--<a class="btn btn-mini add-more-text controls hide" href="#"><i class="icon-arrow-down"></i> Add More Text</a>-->
			    	  <a class="btn btn-mini submitable controls" style="visibility:hidden" href="#"><i class="icon-check"></i> Finished Typing</a>
			    	  </form>
			    	
			    </div>
			  

		    </div>
		    <div class="overlay-topper hide"><span></span><a class="btn btn-small" href="#"><i class="icon-remove"></i> Close</a></div>

		    <!-- BG Images -->
		    <%bg_event_type = @scene.love_scene? ? LovePoseEvent : BackgroundImageEvent%>
		    <div class="overlay bg-image" style="display:none">
		    	<ul class="thumbnails">
		      <%bg_event_type.file_list.each do |option|%>
		        <li class="span2">
		        <%=form_tag update_event_project_scene_path(@project, @scene)%>
		          <input type="hidden" name="event[type]" value="<%=bg_event_type%>">
		          <input type="hidden" name="event[<%=bg_event_type.bg_attribute%>]" value="<%=option.url%>">
		          <input type="hidden" name="event_id" class="event_id" value="">
		          <input type="hidden" name="event[order_index]" class="event_order" value="<%=@event_index%>">
		          <a class="submitable thumbnail">
		          	<%= image_tag option.url%><p><%=option.title%></p>
		          </a>
		          
		        </form>
		        </li>
		      <%end%>
		      </ul>
		    </div>

		    <!-- Music -->
		    <div class="overlay music" style="display:none">
		    <ul class="graphic">
		    	<%=form_tag update_event_project_scene_path(@project, @scene)%>
		          <input type="hidden" name="event[type]" value="BackgroundMusicEvent">
		          <input type="hidden" name="event[filename]" value="">
		          <input type="hidden" name="event_id" class="event_id" value="">
		          <input type="hidden" name="event[order_index]" class="event_order" value="<%=@event_index%>">
		          <li class="">
		          	<a class="silence" href="#">(Silence)</a><button class="submitable btn btn-small" href="#">Choose</button>
		          </li>
		        </form>
		      <%BackgroundMusicEvent.file_list.each do |option|%>
		    
		        <%=form_tag update_event_project_scene_path(@project, @scene)%>
		          <input type="hidden" name="event[type]" value="BackgroundMusicEvent">
		          <input type="hidden" name="event[filename]" value="<%=option.url%>">
		          <input type="hidden" name="event_id" class="event_id" value="">
		          <input type="hidden" name="event[order_index]" class="event_order" value="<%=@event_index%>">
		          <li class="<%=option.category%>">
		          	<a class="" href="<%=option.url%>"><%=option.title%></a><button class="submitable btn btn-small" href="#">Choose</button>
		          </li>
		        </form>
		        
		      <%end%>
		      </ul>
		    </div>


		    <!-- Normal Poses -->
			    <%@project.characters.each do |character|%>
			    <%next if character.is_narrator?%>
			      <div class="overlay poses-for-<%=character.id%>" style="display:none">
			      	<ul class="thumbnails">
			      	<%category = @scene.love_scene? ? "LovePose" : "Pose"%>
				    <%character.get_poses(category,session_obj).each do |option|%>
				      <%=form_tag update_event_project_scene_path(@project, @scene)%>
				        <li class="span2">
				        <input type="hidden" name="event[type]" value="CharacterPoseEvent">
			            <input type="hidden" name="event[filename]" value="<%=option.url%>">
			            <input type="hidden" name="event[character_id]" value="<%=character.id%>">
			            <input type="hidden" name="event[order_index]" class="event_order" value="<%=@event_index%>">
			            <%unless @scene.love_scene?%>
			              <input type="hidden" name="event[subfilename]" value="<%=option.face%>" class="subfilename">
			            <%end%>
			            <input type="hidden" name="event_id" class="event_id" value="">
				  	     <a class="submitable thumbnail">
				  	    <%=image_tag(option.thumbnail)%><p><%=option.title%></p>
				  	    </a>
				  	  </li>
				  	  </form>
				  	<%end%>
				    </ul>
			      </div>
			      <%if !@scene.love_scene?%>
				      <div class="overlay faces-for-<%=character.id%>" style="display:none">
				      	<ul class="thumbnails">
					    <%character.get_poses("Face",session_obj).each do |option|%>
					      <%=form_tag update_event_project_scene_path(@project, @scene)%>
					        <li class="span2">
					        <input type="hidden" name="event[type]" value="CharacterPoseEvent">
				            <input type="hidden" name="event[subfilename]" value="<%=option.url%>">
				            <input type="hidden" name="event_id" class="event_id" value="">
				            <input type="hidden" name="event[order_index]" class="event_order" value="<%=@event_index%>">
				            <input type="hidden" name="event[character_id]" class="character_id">
					  	     <a class="submitable thumbnail">
					  	    <%=image_tag(option.thumbnail)%><p><%=option.title%></p>
					  	    </a>
					  	  </li>
					  	  </form>
					  	<%end%>
					    </ul>
				      </div>
			      <%end%>

			    <%end%>
		


		  </div>
		</td>
	</tr>
</table>
 <div id="sm2-container">
  <!-- SM2 flash goes here -->

 </div>
<script>
  //Note: Make sure that events and images always synv up
  <%event_list = [@scene].map{|scene| scene.get_ordered_events}.flatten%>
  var events = <%=json_escape(event_list.to_json(:methods=>[:event_type, :get_character_name], :except=>[:created_at, :updated_at, :character_type]).html_safe)%>;
  var images = <%=event_list.map{|e|compiled_image(e)}.to_json.html_safe%>;
  window.onload = function(){
  	<%if current_event%>
  	  setCurrentEvent($("#row<%=current_event.id%>"));
  	<%end%>
  }
</script>

app/views/scenes/new.html.erb
<h1>New scene</h1>

<%= render 'form' %>

<%= link_to 'Back', scenes_path %>