config/routes.rb
MyVisualNovel::Application.routes.draw do


  resource :user_sessions
  match 'play/:id/null' => proc { [404, {}, ['']] }#for IE9 SoundManager
  match 'play/:id/:basename' => 'projects#play', :as=>:play
  resources :projects do
    resources :characters
    resources :scenes do
      member do
        post :update_event
        post :reorder
      end
      resources :events
    end
  end
  match 'projects/:project_id/toggle_character/:character_type' => 'characters#toggle', :as=>:toggle_character
  match 'events/:id/delete' => 'events#delete', :as => :delete_event
  match 'events/:id/moveup' => 'events#moveup', :as => :moveup_event
  match 'events/:id/movedown' => 'events#movedown', :as => :movedown_event
  match 'play/:id/:basename/scene/null' => proc { [404, {}, ['']] }#for IE9 SoundManager
  match 'play/:id/:basename/scene/:scene_id' => 'projects#play', :as=>:play_scene 

  resources :users do
    member do
      put :change_password
    end
  end

  match 'signup' => 'users#new', :as => :signup
  match 'logout' => 'user_sessions#destroy', :as => :logout
  match 'login' => 'user_sessions#new', :as => :login
  match 'main/terms' => 'main#terms_of_service', :as=>:terms_of_service
  match 'forum' => "main#forum", :as=>:forum
  match 'not_found' => 'main#not_found', :as => :not_found
  match 'main/cookie' => "main#cookie", :as=>:cookie
  match 'i' => "imager#get", :as=>:imager
  # match 'i/BackgroundImage/:folder/:filename.:format' => "imager#get", :as=>:imager
  root :to => 'main#index'


end

app/models/project.rb
class Project < ActiveRecord::Base
   attr_accessible :title, :public, :character_ids, :basename, :author
   before_create :setup_data
   has_many :characters, :dependent=>:destroy
   has_many :scenes, :dependent=>:destroy
   validates_presence_of :title
   before_save :set_basename
   belongs_to :owner, :polymorphic => true

   scope :for_owner, lambda { |owner| {:conditions => {:owner_id => owner.id.to_s }} }

   def default_title
   	"Dream Date"
   end
   def play_path
      "/play/#{id}/#{basename}"
   end
   def owner?(user)
     self.owner_id == user.id.to_s
     self.owner_type == user.class.to_s
   end
  def temp?
    self.owner_type.to_s != "User"
  end
  def middle_index
    (scenes.count.to_f/2).ceil
  end


protected
   def set_basename
      self.basename = self.basename.gsub("-"," ").gsub(/[^0-9A-Za-z\s]/, '').gsub(" ","-") if basename_changed?
      self.basename = self.title.gsub(/[^0-9A-Za-z\s]/, '').gsub(" ","-") if basename.nil?
   end
   def setup_data
   	  self.characters << Ami.new
   	  self.characters << Narrator.new
      self.characters << Ajax.new
   end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :get_project, :only=>[:show, :edit, :update, :destroy]
  # GET /projects
  # GET /projects.json
  def index
    @backlink = root_path
    @projects = session_obj.projects
    @include_cool_font = @projects.map{|p|p.title.titleize}.join
    if @projects.empty?
      redirect_to new_project_path and return
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end
  def play
    @html_class = "player"
    @project = Project.find_by_id_and_basename(params[:id],params[:basename])
    @after_events = []
    @before_events = []
    if @project && (@project.public? || @project.owner?(session_obj))
      if params[:scene_id]
        @only_scene = true
        @scenes = [Scene.find(params[:scene_id])]
      else
        @only_scene = false
        @project.increment!(:views)
        @scenes = @project.scenes.ordered
      end
      if @project.temp?
        flash.now[:notice] = "Make sure to login to save your work."
      end
      if @scenes.empty?
        flash[:notice] = "Please add some scenes first."
        redirect_to project_path
        return
      end

    else
      not_found
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @backlink = projects_path
    #@page_title = @project.title
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new
    @backlink = root_path

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @backlink = project_path(@project)
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])
    first_project = session_obj.projects.empty?
    @project.owner_id = session_obj.id
    @project.owner_type = session_obj.type
    set_adult_cookie
    respond_to do |format|
      if @project.save
        if first_project
          flash[:notice] = "Congrats on starting your first visual novel! We gave you an example scene to get you up and running."
          #TODO: Add Example Scene
          pack = EventPacks.starter_scene(@project).first
          scene = @project.scenes.new(:custom_description=>pack.name)
          scene.events = pack.events
          scene.save!
          scene.events.first.reorder_indexes
        end
        format.html { redirect_to @project }
        format.json { render json: @project, status: :created, location: @project }
      else
        @backlink = projects_path
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to project_path(@project) }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end
  def get_project
    @project = Project.find_by_id(params[:id])
    if @project.nil?
      not_found
      return false
    elsif !@project.owner?(session_obj)
      not_authorized
      return false
    end
  end
  # # DELETE /projects/1
  # # DELETE /projects/1.json
  def destroy

    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/edit.html.erb
<h1><%= coolify @project.title%></h1>
<p class="lead">&nbsp;</p>
<%=form_for @project do |f|%>
  <table class="table">
    <tr><td class="attr"><%=f.label :title%></td><td><%=f.text_field :title%></td></tr>
    <tr><td class="attr"><b>URL: </b>http://myvisualnovel.com/play/<%=@project.id%>/</td><td><%=f.text_field :basename%></td></tr><tr>
      <td class="attr">This story is:</td><td>
      <table class="table-verycondensed"><!-- only in a table because ie9 won't display it correctly -->
      <tr><td><%=f.radio_button :public, :true%></td><td><b>Public</b> - Others will be allowed to view it and make comments.</td></tr>
      <tr><td><%=f.radio_button :public, :false%></td><td><b>Private</b> - Only you can view it while logged in.</td></tr></table>
    </td></tr>
    <tr>
      <td class="attr"><%=f.label :author, "Author's Name"%><br/></td>
      <td><%=f.text_field :author, :placeholder=>"Your Name Here"%><br/><small>Put your name to appear in the credits!</small></td>
    </tr>
  </table>
  <button type="submit" class="btn btn-primary">Change</button>


<%end%>
  <%= form_for([@project], :method => :delete) do |f|%>   
        <a class="btn btn-small delete-scene">Delete Novel</a>
  <%end%>

app/views/projects/index.html.erb
<h2>Edit My Visual Novels</h2>

 <ul class="thumbnails">
  <%session_obj.projects.each do |project|%>
    <li class="span3">
      

      <%scene = Scene.for_project(project).at(project.middle_index).first%>
      <a href="<%=project_path(project)%>" class="thumbnail tiny-viewer" style="position:relative;">
        <%=render :partial=>"scenes/thumbnail", :locals=>{:scene=>scene}%>
        <p><%=coolify project.title%></p> 
      </a>
      <p>
        <a class="btn btn-small" href="<%=project_path(project)%>" title="Change it!"><i class="icon-pencil"></i> Edit</a>
        <a class="btn btn-small btn-primary" href="<%=project.play_path%>" title="Watch it!"><i class="icon-play icon-white"></i> Play</a>
        <%if project.public?%>
        <a class="btn btn-small share-link" href="#" title="To make private, go to Edit > Customize"><i class="icon-share"></i> Share</a>
        <%end%>
      </p>
      <p class="share">
      <small>
        Cut-and-paste this URL to share: <small><%=play_url(project.id, project.basename)%></small>
      </small>
      </p>
      <small><%=pluralize(project.views, 'view') if project.views > 0%></small>
      
    </li>
  <%end%>
</ul>
<p>&nbsp;</p>
<h3><a href="<%=new_project_path%>">Start a New Visual Novel</a></h3>
<p>&nbsp;</p>
<h3>View Visual Novels Made By Others</h3>

<p class="muted">(Coming Soon)</p>

app/views/projects/new.html.erb
<h2>Choose a title for your story</h2>

<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <input name="project[title]" type="text" class="" placeholder="Dream Date">
  <div class="actions">
    <%if has_adult_cookie?%>
      <button class="btn btn-primary submitable">GO</button>
    <%else%>
      <br/><p>Also, you have to be at least 18 years old to use this website.</p>
      <p><button class="btn btn-primary submitable">I'm 18 or older</button></p>
      <a href="/" class="btn btn-small">I'm not</a>
    <%end%>
  </div>
<% end %>

app/views/projects/play.html.erb
<%content_for :javascript do%>
 <%=javascript_include_tag("imagesloaded","soundmanager2/soundmanager2","viewer","simple-slider.min")%>
<%end%>
<%
      unless @only_scene
        author = @project.author.blank? ? link_to("ADD YOUR NAME HERE",edit_project_path(@project.id)) : (@project.author.upcase)
        credits = "
        <h4>By
        #{author}</h4>


        Character Art by
        T.O.P.



        Music by
        JEWELBEAT"
        @before_events << TitleCardEvent.text("<h1>".html_safe+coolify(@project.title)+"<h1>".html_safe)
        @after_events << TitleCardEvent.text(simple_format(credits)) 
      end
      event_list = @scenes.map{|scene| scene.get_ordered_events}.concat(@after_events).prepend(@before_events).flatten

%>

        <%if has_adult_cookie? || session_obj.projects.present?%>
        <script>
          var scenes = <%=json_escape(event_list.to_json(:methods=>[:event_type, :get_character_name], :except=>[:created_at, :updated_at]).html_safe)%>;
          var images = <%=event_list.map{|e|compiled_image(e)}.to_json.html_safe%>;
          
        </script>
          <!-- Stage Viewer -->
          <div class="viewer">
          <%=image_tag BackgroundImageEvent.default.get_file, :class=>"characters hide img-rounded", :id=>"bg-content"%>
            <div class="glassbox" style="display:none">
              <%=image_tag "glassbox.png", :class=>"glass"%>
              <div class="speaker"></div>
              <div class="textarea" id="textarea">

              </div>
            </div>

          </div>
          <div style="text-align:left" id="sound-controls">
          <a id="pause-button" class="btn btn-mini" href="#"><i class="icon-pause"></i></a>
          <a class="btn btn-mini" href="#" title="Mute"><i class="icon-volume-up"></i></a>
          <input id="volume-control" value="100" type="text" data-slider="true" data-slider-theme="volume" data-slider-highlight="true" data-slider-range="0,100">
          </div>
        <%else%>
        <script>
          var scenes = [];
        </script>
        <div id="title-wrapper">
          <div id="title">
          <div><div>
            <h3>You must be 18 or older to view this visual novel.</h3>
            <p><a href="<%=cookie_path(:redirect_to=>@current_uri)%>" class="btn btn-primary">I'm 18 or older</a></p>
            <p><a href="/" class="btn btn-small">I'm not</a></p>
          </div></div>
          </div>
        </div>
        <%end%>
 <div id="sm2-container">
  <!-- SM2 flash goes here -->

 </div>
 <p>&nbsp;</p>
 <p>
  <%if @project.owner?(session_obj)%>
    This visual novel is set to <a href="<%=edit_project_path(@project)%>"><b><%=@project.public? ? "Public" : "Private"%></b></a><br/>
    <%if @project.public?%>
    <small>Cut-and-paste the URL to share:<br/><%=play_url(@project.id, @project.basename)%></small>
    <%end%>
  <%else%>
  &nbsp;
  <%end%>
 </p>
<%if @project.public? && !@only_scene%>
<div id="disqus-comments">
<h2>Leave a Comment</h2>
<div id="disqus_thread"></div>
    <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'myvisualnovel'; // required: replace example with your forum shortname
        var disqus_identifier = '/projects/<%=@project.id%>/';
        var disqus_title = "<%=@project.title%>";

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.defer = true; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
    <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>

<%end%>
</div>

app/views/projects/show.html.erb
<h1><%= coolify @project.title%></h1>
<p class="lead">&nbsp;</p>
<h2>What will you do?</h2>
 <ul class="thumbnails">
    <li class="span2">
      <a href="<%=@project.play_path%>" class="thumbnail" style="position:relative;" title="Watch It!">
          <%middle_index = @project.middle_index%>
          <%scene = Scene.for_project(@project).at(middle_index).first%>
          <%=render :partial=>"scenes/thumbnail", :locals=>{:scene=>scene, :play=>true}%>
          <p>Play the Story!</p> 
      </a>
    </li>
    <li class="span2">
      <a href="<%=project_characters_path(@project)%>" class="thumbnail" style="" title="Change Their Names">
      <%=image_tag @project.characters.shuffle.first.icon%>
      <p>Edit Characters</p></a>
    </li>
    <li class="span2">
      <a href="<%=edit_project_path(@project)%>" class="thumbnail" title="">
          <%=image_tag "tools2.jpg"%>
          <p>Customize</p> 
      </a>
    </li>    
</ul>

<%if @project.scenes.present?%>

  <h2>Add to the Script</h2>

    <%sortable = @project.scenes.count > 1%>
    <ul class="thumbnails" id="<%="sortable" if sortable%>">
      <% @project.scenes.ordered.each do |scene| %>
      <li class="span2" data-id="<%=scene.id%>" data-url="<%=reorder_project_scene_path(@project, scene)%>">
        <a href="<%=edit_project_scene_url(@project, scene)%>" class="thumbnail tiny-viewer" style="position:relative;" title="<%=sortable ? "Drag to Rearrange" : "Edit it"%>">
          <%= render :partial=> "scenes/thumbnail", :locals=>{:scene=>scene}%>
        <p><%=scene.get_description%></p>
      </a>
      </li>
  
      <% end %>
    </ul>

<%end%>
<p class="lead">&nbsp;</p>
  <h2>Add A New Scene</h2>
  <ul class="thumbnails event-packs">
    <%scenes = EventPacks.locations(@project)%>
    <% scenes.each_index do |i| %>
      <li class="span2">
        <%=form_for [@project, Scene.new] do |f|%>
          <%event_pack = scenes[i]%>
          <a href="#" class="submitable thumbnail" title="Add This Scene!">
          <input type="hidden" value="<%=event_pack.love_scene%>" name="scene[love_scene]">
          <input type="hidden" value="<%=i%>" name="scene[initial_event_pack]">
          <%=image_tag event_pack_image(event_pack), :alt=>event_pack.name%>
            <p><span><%=event_pack.name%></span>
              <br/><small class='muted'><i class="icon-music"></i> <%=event_pack.music%></small>
            </p>
          </a>
        <%end%>
      </li>
    <%end%>
      <li class="span2">
        <%=form_for [@project, Scene.new] do |f|%>
          <a href="#" class="submitable thumbnail" title="Start A New Scene">
            <%=image_tag "blur4.jpg", :alt=>"Blank Scene"%>
            <p><span>New Blank Scene</span></p>
          </a>
        <%end%>
      </li>
      <li class="span2">
        <%=form_for [@project, Scene.new] do |f|%>
          <a href="#" class="submitable thumbnail" title="Start A New Scene">
            <input type="hidden" value="1" name="scene[love_scene]">
            <%=image_tag "blur2.jpg", :alt=>"Blank Love Scene"%>
            <p><span>New Blank Love Scene</span></p>
          </a>
        <%end%>
      </li>
    </ul>