config/routes.rb
MyVisualNovel::Application.routes.draw do


  resource :user_sessions
  match 'play/:id/null' => proc { [404, {}, ['']] }#for IE9 SoundManager
  match 'play/:id/:basename' => 'projects#play', :as=>:play
  resources :projects do
    resources :characters
    resources :scenes do
      member do
        post :update_event
        post :reorder
      end
      resources :events
    end
  end
  match 'projects/:project_id/toggle_character/:character_type' => 'characters#toggle', :as=>:toggle_character
  match 'events/:id/delete' => 'events#delete', :as => :delete_event
  match 'events/:id/moveup' => 'events#moveup', :as => :moveup_event
  match 'events/:id/movedown' => 'events#movedown', :as => :movedown_event
  match 'play/:id/:basename/scene/null' => proc { [404, {}, ['']] }#for IE9 SoundManager
  match 'play/:id/:basename/scene/:scene_id' => 'projects#play', :as=>:play_scene 

  resources :users do
    member do
      put :change_password
    end
  end

  match 'signup' => 'users#new', :as => :signup
  match 'logout' => 'user_sessions#destroy', :as => :logout
  match 'login' => 'user_sessions#new', :as => :login
  match 'main/terms' => 'main#terms_of_service', :as=>:terms_of_service
  match 'forum' => "main#forum", :as=>:forum
  match 'not_found' => 'main#not_found', :as => :not_found
  match 'main/cookie' => "main#cookie", :as=>:cookie
  match 'i' => "imager#get", :as=>:imager
  # match 'i/BackgroundImage/:folder/:filename.:format' => "imager#get", :as=>:imager
  root :to => 'main#index'


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="<%=@html_class || "normal"%>">
<head>
  <%@page_title = @page_title || humanize_title(@current_uri)%>
  <title><%=wrap_title @page_title.titleize%></title>
  <%= stylesheet_link_tag "bootstrap.css","inlineplayer","flashblock","simple-slider","simple-slider-volume","application", :cache=>"mvn" %>
<!--[if lt IE 9]>
  <%=stylesheet_link_tag "ie8"%>
<![endif]-->
  <%= csrf_meta_tags %>
  <%if true%>
  <%if @project.try(:title) || @include_cool_font%>
    <%text = @include_cool_font || @project.title.titleize%>
    <link href='http://fonts.googleapis.com/css?family=Great+Vibes&text=<%=text.gsub(/[^0-9A-Za-z\s]/, '')%>' rel='stylesheet' type='text/css'>
  <%end%>
  <%end%>
</head>
<body class="<%=@body_class || ""%>">
<%= yield(:head) || "" %>
<div style="position:relative">
<div class="navbar">
          <div class="navbar-inner">
            <div class="container">
              <div class="nav">

                    <ul class="breadcrumb">
                    <li><%=link_to "Home", root_url%> <span class="divider">/</span></li>
                    <li><%=link_to "Forum", forum_path%> <span class="divider">/</span></li>
                    <%unless session_obj.projects.empty?%>
                      <li><%=link_to "My Visual Novels", projects_path%> <span class="divider">/</span></li>
                    <%end%>
                    <%if @project && !@project.new_record?%>
                      <li><%=link_to coolify(@project.title), @project%> <span class="divider">/</span></li>
                    <%end%>
                    <%if @scene%>
                      <li><%=link_to @scene.get_description, edit_project_scene_path(@project, @scene)%> <span class="divider">/</span></li>
                    <%end%>
                    <li style="float:right">
                    <%if logged_in?%>
                      <%=link_to "Logout", logout_path%>
                    <%else%>
                      <%=link_to "Login", login_path%>
                    <%end%>
                   </li>
                    </ul>
                    
                </li>
              </div>
            </div>
          </div>
        </div>
<div class="container-narrow">
  <div class="jumbotron">
  <%if notice%>
      <div class="alert alert-info">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= notice%>
      </div>
  <%end%>
  <noscript>
    <div class="alert text-error">
      You need Javascript enabled to view or play visual novels.
      </div>
  </noscript>
  <%= yield %>
  </div>
</div>
</div>
<%if @backlink%>
  <a id="backlink" class="carousel-control left" href="<%=@backlink%>?backlink=<%=@current_uri%>" >&lsaquo;<!--<br/><span class="backlink"><%=humanize_title(@backlink)%></span></a>-->
<%end%>
<%if @nextlink = @default_nextlink || @nextlink%>
  <a id="nextlink" class="carousel-control right" href="<%=@nextlink%>">&rsaquo;<!--<br/><span class="backlink"><%=humanize_title(@nextlink)%></span></a>-->
 
<%end%>
<%= javascript_include_tag "jquery","jquery-ui-1.10.3.custom.min.js","bootstrap.js","jquery.placeholder.min","slide","popups","application", :cache=>"mvn" %>
<%= yield(:javascript) || "" %>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-41467885-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
</body>
</html>